
metricbeat.config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
    reload.period: 10s
metricbeat.modules:
-   module: docker
    metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true 

output.elasticsearch:
    hosts: ["elasticsearch:9200"]
setup.kibana:
    host: "kibana:5601"